### ISSUE TITLE
Frontiers

### ISSUE THREAD

**Issue by tiagonovo0** [larics/frontier_exploration_3d#2]
Hello again,
From the original method (fbet) were you able to run it and get all the octomaps? In my case there are very few frontier cells and they are not shownin a precise cluster. The cells are very distant from each other and therefore I'm not getting a frontier_goal_cell.

Here you can see a print of the occupied area with only one frontier cell alone.
![Screenshot from 2020-06-03 01-00-39](https://user-images.githubusercontent.com/61195838/83581142-de523280-a535-11ea-9b2b-dcf3e101c3c2.png)

Did you noticed anything in your case?

**Comment by AnaBatinovic** [comment]
Hi @tiagonovo0 , 
yes, I was able to run the FBET method and I got all the octomaps, but the frontier cells were so illogical (similar to your case). So, I changed their frontier detection method and clustering algorithm. 
I suggest you to take a look at the FBET code and to try to understand it and fit it to your data. For instance, in the original method, clustering is just erasing every k point, which is not useful in my case.  
If you have any questions regarding ideas on changing the original algorithm or you get stuck, feel free to contact me again.

**Comment by tiagonovo0** [comment]
I am new at this type of projects. I would like to try to implement your version of the FBET code, but when compiling your project I get an error  because of the missing mean_shift_clustering package. I could not find any repository that could give me this package. Can you help me here?

**Comment by AnaBatinovic** [comment]
I greatly appreciate your interest in our work.

Unfortunately, I am not able to provide you the clustering algorithm at this moment. The current implementation builds upon a number of other packages that are actively developed by various members of our group. These packages include UAV models and controllers, communication protocols, Gazebo worlds and plugins, trajectory generators, and so on. Due to these reasons, code is currently not suitable for sharing. 

As soon as we are satisfied with its state and ensure that there aren’t any dependency issues, we will publish the code in its entirety with detailed documentation on a publicly available GitHub repository with an open-source license.

**Comment by fpetric** [comment]
As @AnaBatinovic said, we are not able to share the mean_shift_clustering at this time (due to dependencies which include some private repositories), but you are welcome to use any existing clustering algorithms you find suitable for your application (it may take some tweaking in the FBET code for which the support should be sought at the original FBET repository). Closing the issue until we are ready to release the code in all its glory. We will also probably switch our repo to private to avoid further issues of this sort and make it public when it is ready to be published.
