### ISSUE TITLE
how to install ”mean_shift_clustering“ on ubuntu 16

### ISSUE THREAD

**Issue by hjlstudy** [larics/frontier_exploration_3d#3]

**Comment by AnaBatinovic** [comment]
Please refer to issue [#2 ](https://github.com/larics/frontier_exploration_3d/issues/2).

**Comment by fpetric** [comment]
as discussed in #2, we are not able to share the mean_shift_clustering at this time (due to dependencies which include some private repositories), but you are welcome to use any existing clustering algorithms you find suitable for your application (it may take some tweaking in the FBET code for which the support should be sought at the original FBET repository). Closing the issue until we are ready to release the code in all its glory. We will also probably switch our repo to private to avoid further issues of this sort.
